username: 0ex-d
title: Precious Akin
description: Software Developer - Portfolio
baseurl:
encoding: utf-8
locale: en_GB
menu:
    - page: Using IPFS with Golang
      url: /ipfs-golang
    - page: RPC + Rust for Arbitrum Onchain Experiment
      url: /rpc-in-rust-experiment
